version: '3.8'
services:

  postgres:
    image: postgres:14
    container_name: dav-proof-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data

  nest-api:
    container_name: ms-dav
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres:
    name: dav-proof-postgres
